# ClearML configuration file
api {
  web_server: http://133.8.202.70
  api_server: http://133.8.202.70:8008
  credentials {
    "access_key" = "E6YGZ6HLNPXQ94G47BAX"
    "secret_key" = "pmmIsm5LzXeUuPIoeIhWqt8BybcrMaLLVGzv78ksiQ4PsiEW4u"
  }
}