api {
  web_server: http://133.8.202.70
  api_server: http://133.8.202.70:8008
  credentials {
    "access_key" = "NQZPCB21ZLQL3WIQU8QK"
    "secret_key" = "KWxOtVuORweduVcXwnULkyEMg3WVV8XBTSEhQJ9XW2Bf63toih"
  }
}